resource_group_name = "Infra-drift-RG"
location            = "eastus"
account_tier        = "Standard"
account_replication_type = "LRS"
storage_account_name = "driftteststorage01"
container_access_type = "blob"
